## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [3]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Tunceli,TR,81.46,scattered clouds,39.1083,39.5471,Grand Hotel Şaroğlu
1,4,Iralaya,HN,86.09,broken clouds,15.0000,-83.2333,Iglesia morava renovada
2,9,Cayenne,GF,77.04,mist,4.9333,-52.3333,Hôtel Le Dronmi
3,11,Victoria,HK,86.32,light rain,22.2855,114.1577,Mini Hotel Central
4,12,Kavaratti,IN,82.42,scattered clouds,10.5669,72.6420,Hotels in Lakshadweep Islands

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,2,Tunceli,TR,81.46,scattered clouds,39.1083,39.5471,Grand Hotel Şaroğlu
1,4,Iralaya,HN,86.09,broken clouds,15.0000,-83.2333,Iglesia morava renovada
2,9,Cayenne,GF,77.04,mist,4.9333,-52.3333,Hôtel Le Dronmi
3,11,Victoria,HK,86.32,light rain,22.2855,114.1577,Mini Hotel Central
4,12,Kavaratti,IN,82.42,scattered clouds,10.5669,72.6420,Hotels in Lakshadweep Islands
...,...,...,...,...,...,...,...,...
222,671,Ranot,TH,78.62,overcast clouds,7.7777,100.3213,Pakbanglake resort ปากบางเลค รีสอร์ท
223,672,Mantua,IT,77.05,few clouds,45.1667,10.7833,Hotel la Favorita
224,673,Balikpapan,ID,76.50,overcast clouds,-1.2675,116.8289,ibis Balikpapan
225,678,Daru,PG,76.78,overcast clouds,-9.0763,143.2092,Daru Lodge
226,679,Dayong,CN,83.88,broken clouds,25.0209,118.2898,Haiyue Express Hotel

In [5]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City']=='San Patricio']
vacation_end = vacation_df.loc[vacation_df['City']=='San Patricio']
vacation_stop1 = vacation_df.loc[vacation_df['City']=='Houma']
vacation_stop2 = vacation_df.loc[vacation_df['City']=='Stephenville'] 
vacation_stop3 = vacation_df.loc[vacation_df['City']=='Pahrump']

In [22]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start['Lat'].to_numpy()[0],vacation_start['Lng'].to_numpy()[0]
end = vacation_end['Lat'].to_numpy()[0],vacation_end['Lng'].to_numpy()[0]
stop1 = vacation_stop1['Lat'].to_numpy()[0],vacation_stop1['Lng'].to_numpy()[0]
stop2 = vacation_stop2['Lat'].to_numpy()[0],vacation_stop2['Lng'].to_numpy()[0]
stop3 = vacation_stop3['Lat'].to_numpy()[0],vacation_stop3['Lng'].to_numpy()[0]

In [23]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
waypoints = [stop1,stop2,stop3]
directions = gmaps.directions_layer(start, end,waypoints=waypoints)
directions.travel_mode = 'DRIVING'
fig.add_layer(directions)
fig

Figure(layout=FigureLayout(height='420px'))

In [24]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,141,San Patricio,US,88.88,clear sky,28.0170,-97.5169,"Motel 6 Sinton, TX"
1,381,Houma,US,86.00,clear sky,29.5958,-90.7195,Courtyard by Marriott Houma
2,582,Stephenville,US,84.94,clear sky,32.2207,-98.2023,La Quinta Inn & Suites by Wyndham Stephenville
3,630,Pahrump,US,76.17,clear sky,36.2083,-115.9839,Best Western Pahrump Oasis

In [25]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [26]:
# 11a. Add a marker layer for each city to the map.
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))